### ISSUE TITLE
can't find importAuthenticationTemplate?

### ISSUE THREAD

**Issue by kzKallisti** [bitauth/libauth#107]
Hello,

I'm trying to import and use the function `importAuthenticationTemplate` but I am not able to import it.

example code:
```
import { importAuthencicationTemplate, authenticationTemplateP2pkh }

const template = importAuthenticationTemplate(authenticationTemplateP2pkh);
```

result: `Uncaught SyntaxError: ambiguous indirect export: importAuthenticationTemplate`

alternate approach:
```
import * as libauth from "@bitauth/libauth";

const template = libauth.importAuthenticationTemplate(authenticationTemplateP2pkh);
```

result: `libauth.importAuthenticationTemplate is not a function`

Manually searching for the function:
```
cd node_modules/@bitauth/libauth
grep -R "importAuthenticationTemplate"
```
result: `<no result>`

I found it interesting that the "schema" dir is also not visible on the code coverage tool: https://app.codecov.io/gh/bitauth/libauth/tree/master/src/lib

The function is clearly defined in https://github.com/bitauth/libauth/blob/master/src/lib/schema/authentication-template.ts, exported in https://github.com/bitauth/libauth/blob/master/src/lib/schema/schema.ts, and exported again in https://github.com/bitauth/libauth/blob/master/src/lib/lib.ts, so I'm at quite a loss for why this function won't import :(

**Comment by kzKallisti** [comment]
Even after deleting my node_modules folder and doing `yarn install` I am still not able to import the function.

If I look at node_modules/@bitauth/libauth/build/module/lib/lib.js, I see that `export @ from './schema/schema';` is NOT present.

**Comment by kzKallisti** [comment]
A little more digging... I guess it's because npm still has version 1.19.1, and master (which I think the official docs on libauth.org are following) is actually 2.0.0-alpha.8.

Upgrading to libauth 2.0.0-alpha.8 makes my app break when I try to use `deriveHdPrivateNodeFromSeed` in a way that does work with v1.19.1.

```
import { deriveHdPrivateNodeFromSeed } from "@bitauth/libauth";
import { crypto } from "@/util/crypto"; // re-exports instantiated  crypto functions from libauth
const { secp256k1, ripemd160, sha256, sha512 } = crypto;

const seed = "..."; // string generated by bip39 library
const hdMaster = deriveHdPrivateNodeFromSeed({ sha512 }, seed);
```

```
 Uncaught (in promise) RangeError: source array is too long
    flattenBinArray hex.js:66
    flattenBinArray hex.js:64
    instantiateHmacFunction hmac.js:19
    hmacSha512 hmac.js:54
    deriveHdPrivateNodeFromSeed hd-key.js:27
    HdNodeService HdNodeService.jsx:20
   ...
```

**Comment by kzKallisti** [comment]
Got everything working as expected now.

Summary of changes:

- did not need to use the instantiateSecp256k, instantiateSha256k, etc functions at all, can just import {secp256k, sha256, ...} directly from libauth now.

- did not need to pass the `crypto` object to any of the HdNode functions anymore, it will use the built-in implementations automatically.

- `importAuthenticationTemplate` imports as expected. :innocent:
